---
output:
  pdf_document: default
  html_document: default
---
# Tech Stack {#tech-stack}

Als Tech Stack wird die Summe der verwendeten Technologien bezeichnet. Dazu gehören zum Beispiel die Programmiersprache, das Framework für die Web-Applikation, die Datenbanksoftware, aber auch die Entwicklungsumgebung und weitere Software, die im Entwicklungsprozess verwendet wird. [@Küllenberg2020, S.61-67]

## Framework

Zuallererst muss das Framework zur Erstellung der Web-Applikation gewählt werden. Dieses legt die zu verwendende Programmiersprache fest und setzt möglicherweise Restriktionen in Bezug auf weitere Software. Eine Web-Applikation zeichnet sich dadurch aus, dass sie im Webbrowser ausführbar ist [@webappdef, S.115]. Der Webbrowser ist in der Lage, Dateien im HTML-Format (HTML: Hyper Text Markup Language [@Baumgarten2002, S.13]) darzustellen. Das HTML-Format spezifiziert dabei ausschließlich die Struktur der Webseite [@Baumgarten2002, S.13]. Um die visuelle Erscheinung der Webseite zu beeinflussen, können Regeln in CSS-Dateien (CSS: Cascading Style Sheet) hinterlegt werden [@Baumgarten2002, S.51]. Für interaktives Verhalten existiert die Sprache JavaScript, die es ermöglicht, das HTML-Dokument dynamisch anzupassen [@Baumgarten2002, S.55].

Ein Framework zur Erstellung von Web-Applikationen bietet ein Grundgerüst für Layout sowie Funktionalität und stellt einen Server bereit. Für das Layout werden beispielsweise makroskopische Komponenten, wie Dashboards und Landing Pages, oder mikroskopische Komponenten, wie Inputs, Tabellen und Plots, bereitgestellt. Die Funktionalität wird abstrahiert und der Zustand der Web-Applikation modelliert. Der Server bearbeitet Anfragen von Clients, also Nutzern der Web-Applikation. Frameworks können in beliebigen Programmiersprachen implementiert werden, solange eine Schnittstelle zwischen der vom Framework verwendeten Sprache und einer dem Browser verständlichen Sprache existiert. Frameworks können hinsichtlich verschiedener Kriterien unterschieden werden. Backend-Frameworks integrieren neben einem Server meist auch noch Datenbanken, wohingegen Frontend-Frameworks ihren Fokus mehr auf den visuellen Part legen. Multipage-Frameworks enthalten mehrere Seiten, wohingegen Singlepage-Frameworks nur eine einzige Seite darstellen. [@framework, S.10-12] 

Für die Bearbeitung dieses Projektes wurde das Framework Shiny gewählt, das in der Programmiersprache R implementiert ist. Hierbei handelt es sich um ein Singlepage-Framework, das als Backend den sogenannten Shiny Server enthält [@Allen2020]. Maßgeblich für die Entscheidung war, dass die beiden Autoren über Erfahrung im Umgang mit R und im Speziellen mit Shiny verfügen. Darüber hinaus zeichnet sich Shiny durch folgende Eigenschaften und Vorzüge aus [@Allen2020]:

* Moderne Templates
* Fokus auf Funktionalität (Erleichterter Programmierprozess)
* Reaktives Zustandsmodell
* Modularisierbarkeit
* Für Anwendungsfall ausreichende Performance
* Einfache Integration von Datenbanken

## Programmiersprache

[R](https://www.r-project.org/) ist eine Multiparadigmen-Programmiersprache [@Chambers2014]. Je nach Anwendungsfall kann somit zum Beispiel objektorientiert oder funktional programmiert werden [@Chambers2014]. R verfügt über einen Pool an Standardbibliotheken und kann einfach durch selbstgeschriebene und frei verfügbare Packages erweitert werden [@r_manual]. Das Comprehensive R Archive Network ([CRAN](https://cran.r-project.org/)) stellt eine Vielzahl von quelloffenen Bibliotheken zur Verfügung wie zum Beispiel {[shiny](https://shiny.rstudio.com/)}, das die Funktionalitäten des Frameworks beinhaltet [@cran_faq]. Die folgenden Tabellen \@ref(tab:pkg-shiny) und \@ref(tab:pkg-programming) geben Aufschluss über die im Projekt verwendeten Packages und ihren Zweck. Packages können von anderen Packages abhängen. Es wird daher darauf verzichtet auf untergeordnete Bibliotheken einzugehen.

| Package | Beschreibung |
| ------- | ----- |
| {[bs4Dash](https://cran.r-project.org/web/packages/bs4Dash/index.html)} [@R-bs4Dash] | AdminLTE-Template |
| {[DT](https://cran.r-project.org/web/packages/DT/index.html)} [@R-DT] | DataTables für {shiny} |
| {[htmltools](https://cran.r-project.org/web/packages/htmltools/index.html)} [@R-htmltools] | HTML-Repräsentation in R |
| {[rclipboard](https://cran.r-project.org/web/packages/rclipboard/index.html)} [@R-rclipboard] | Zwischenablage |
| {[shinydisconnect](https://cran.r-project.org/web/packages/shinydisconnect/index.html)} [@R-shinydisconnect] | Verbindungsverlustbildschirm |
| {[shinyjs](https://cran.r-project.org/web/packages/shinyjs/index.html)} [@R-shinyjs] | Integration von Custom-JavaScript |
| {[waiter](https://cran.r-project.org/web/packages/waiter/index.html)} [@R-waiter] | Ladebildschirm |
Table: (\#tab:pkg-shiny) Packages für {shiny}

| Package | Beschreibung |
| ------- | ----- |
| {[Cairo](https://cran.r-project.org/web/packages/Cairo/index.html)} [@R-Cairo] | PDF-/PNG-/SVG-Erstellung |
| {[DBI](https://cran.r-project.org/web/packages/DBI/index.html)} [@R-DBI] | Datenbankinterface |
| {[dplyr](https://cran.r-project.org/web/packages/dplyr/index.html)} [@R-dplyr] | Datentransformationen |
| {[glue](https://cran.r-project.org/web/packages/glue/index.html)} [@R-glue] | String-Erzeugung |
| {[lubridate](https://cran.r-project.org/web/packages/lubridate/index.html)} [@R-lubridate] | Datumsformat |
| {[RSQLite](https://cran.r-project.org/web/packages/RSQLite/index.html)} [@R-RSQLite] | SQLite-Datenbank |
| {[stringr](https://cran.r-project.org/web/packages/stringr/index.html)} [@R-stringr] | String-Manipulation |
| {[tibble](https://cran.r-project.org/web/packages/tibble/index.html)} [@R-tibble] | Tabellenformat |
| {[purrr](https://cran.r-project.org/web/packages/purrr/index.html)} [@R-purrr] | Funktionale Programmierung |
| {[qrcode](https://cran.r-project.org/web/packages/qrcode/index.html)} [@R-qrcode] | Erstellung von QR-Codes |
| {[renv](https://cran.r-project.org/web/packages/renv/index.html)} [@R-renv] | Packagemanagement |
| {[yaml](https://cran.r-project.org/web/packages/yaml/index.html)} [@R-yaml] | YAML-Dateiformat |

Table: (\#tab:pkg-programming) Packages für die Programmierung

## Datenbank

Zur konsistenten Datenverwaltung wird eine Datenbank benötigt. Datenbanken sind in der Lage, Anfragen von verschiedenen Clients zu bearbeiten und dabei zu gewährleisten, dass bestimmte Regeln hinsichtlich der Datenstruktur und Ausprägung der Daten eingehalten werden [@Bühler2018, S.68ff]. Es existieren verschiedene Datenbankmodelle, unter anderem das Netzwerkdatenbankmodell, das objektorientierte, das hierachische oder das relationale Datenbankmodell [@laudon2015]. Diese unterscheiden sich hinsichtlich der Verknüpfung der beteiligten Daten. Aufgrund der hohen Flexibilität und der weiten Verbreitung wurde das relationale Datenbankmodell ausgewählt. Dieses speichert die Daten in miteinander verknüpften Tabellen [@Bühler2018, S.69-76]. Die Tabellenzeilen enthalten Beobachtungen, die Tabellenspalten stellen die beobachtbaren Merkmale dar. Zur eindeutigen Identifikation erhält jede Zeile eine Identifikationsnummer. Die Spalte der Identifikationsnummern wird als Primärschlüssel (*Primary Key*) bezeichnet [@Bühler2018, S.73]. Um verschiedene Tabellen miteinander zu verknüpfen, werden Identifikationsnummern referenziert. Eine Spalte, die auf einen Primärschlüssel einer anderen Tabelle verweist, wird als Fremdschlüssel (*Foreign Key*) bezeichnet [@Bühler2018, S.70].

Es gibt eine Vielzahl verschiedener relationaler Datenbankmanagementsysteme, die sich hinsichtlich ihrer Anwendungsbereiche und Skalierbarkeit unterscheiden. Für Projekte kleinen und mittleren Umfanges (unter 100.000 Aufrufe / Tag [@whysqlite]) eignet sich [SQLite](https://www.sqlite.org/index.html). Hierbei werden alle Tabellen in einer einzigen Datei mit dem Suffix *.sqlite* gespeichert. Der Zugriff auf die Datenbank erfolgt grundsätzlich über die *Structured Query Language* (SQL). Für die Programmiersprache R gibt es die Packages {DBI} und {RSQLite}, die eine direkte Schnittstelle zur Datenbank bereitstellen.