---
output:
  bookdown::gitbook:
    css: style.css
    config:
      toc:
        before: |
          <li><a href="./">Sensotheka</a></li>
        after: |
          <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
      download: ["pdf", "epub"]
      sharing:
          facebook: false
          twitter: false
    pandoc_args: [ "--csl", "thieme-german.csl"]
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    keep_tex: yes
    citation_package: biblatex
  bookdown::epub_book: default
bibliography: [book.bib, r-bib.bib]
biblio-style: numeric
link-citations: true
always_allow_html: true
geometry: "left=3cm,right=3.5cm,top=2cm,bottom=2cm"
toc-title: Inhaltsverzeichnis
---

\renewcommand{\figurename}{Abbildung}
\renewcommand{\tablename}{Tabelle}
\renewcommand{\listfigurename}{Abbildungsverzeichnis}
\renewcommand{\listtablename}{Tabellenverzeichnis}
\renewcommand{\refname}{Literaturverzeichnis}

\pagenumbering{Roman}

\newpage{}

\listoffigures
\addcontentsline{toc}{section}{Abbildungsverzeichnis}

\newpage{}

\listoftables
\addcontentsline{toc}{section}{Tabellenverzeichnis}

\newpage{}

\pagenumbering{arabic}

```{r, echo=FALSE}
library(shiny)
library(dplyr)

badge <- function(type = c("admin", "mod", "user", "unique", "nn", "fk"), short = FALSE) {
  type <- match.arg(type)
  
  text <- if (short) {
    switch (
      type,
      "admin" = "A",
      "mod" = "M",
      "user" = "B",
      "unique" = "U",
      "nn" = ">= 0",
      "fk" = "FK"
    )
  } else {
    switch (
      type,
      "admin" = "Administrator",
      "mod" = "Moderator",
      "user" = "Benutzer",
      "unique" = "Einzigartig",
      "nn" = "Nicht-negativ",
      "fk" = "Fremdschlüssel"
    )
  }
  
  if (knitr::is_html_output()) {
    htmltools::span(
      class = paste("badge", type),
      text
    )
  } else {
    paste0("[", text, "]")
  }
}

operate_button <- function(operation = c("borrow", "return", "write-off")) {
  operation <- match.arg(operation)
  
  text <- switch(
      operation,
      "borrow" = "Ausleihen",
      "return" = "Zurückgeben",
      "write-off" = "Abschreiben"
    )
  if (knitr::is_html_output()) {
    shiny::actionButton(
    inputId = "",
    label = text,
    icon = shiny::icon(
      name = switch(
        operation,
        "borrow" = "sign-out-alt",
        "return" = "sign-in-alt",
        "write-off" = "balance-scale-right"
      )
    ),
    class = paste0(operation, "-btn"),
    style = "width: 100px; margin-right: 10px;"
  ) %>% htmltools::span()
  }else {
    paste0("[", text, "]")
  }
}

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

# Einführung {#introduction}

Die Verwaltung von Messmitteln bzw. Sensoren am Fachgebiet Fahrzeugantriebe der Technischen Universität Berlin gestaltet sich schwierig. Zurzeit werden Messmittel dezentral verwaltet. Die handelnden Personen besitzen wenig Information über den Ausleihzustand einzelner Messmittel über verschiedene Projekte hinweg. Daher hat sich das Fachgebiet entschlossen, im Rahmen des Moduls "Projekt Fahrzeugantriebe" eine Web-Applikation zur Verwaltung von Messmitteln erstellen zu lassen. Diese Web-Applikation soll die Ausleihe und Rückgabe einzelner Messmittel über einen QR-Code realisieren. Darüber hinaus sollen Messmittel gruppiert, zusätzliche Informationen, wie zum Beispiel Datenblätter, bereitgestellt und der Bestand erfasst werden. Um die unterschiedlichen Verantwortlichkeiten der Akteure zu berücksichtigen, ist zudem eine rechtebasierte Nutzerverwaltung vorzusehen.

Der Inhalt dieses Berichtes umfasst die Dokumentation des Arbeitsprozesses (Kapitel [2](#requirements), [3](#tech-stack) und [4](#workflow)), die Beschreibung des finalen Produktes hinsichtlich Funktionalität (Kapitel [5](#user-guide)) und technischer Umsetzung (Kapitel [6](#technical-guide)) und zeigt zusätzlich Anknüpfungspunkte für Folgeprojekte (Kapitel [7](#discussion)) auf. Ergebnisse werden abschließend diskutiert (Kapitel [7](#discussion)).
